import { IPC_CHANNELS } from '../../shared/ipc-channels';

export type IpcChannelName = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS];

export const IPC_CHANNEL_GROUPS = {
  app: [IPC_CHANNELS.ping, IPC_CHANNELS.appGetPreferences, IPC_CHANNELS.appUpdatePreferences],
  project: [
    IPC_CHANNELS.projectCreate,
    IPC_CHANNELS.projectUpdatePlanning,
    IPC_CHANNELS.projectOpen,
    IPC_CHANNELS.projectClose,
    IPC_CHANNELS.projectInspectPath,
    IPC_CHANNELS.projectSelectDirectory,
    IPC_CHANNELS.projectSelectImageFile,
    IPC_CHANNELS.projectReadImageDataUrl,
    IPC_CHANNELS.projectGetCurrent,
    IPC_CHANNELS.projectSaveSnapshot,
    IPC_CHANNELS.projectListSnapshots,
    IPC_CHANNELS.projectListWritingSessions,
    IPC_CHANNELS.projectRecoverLatestSnapshot,
  ],
  wiki: [
    IPC_CHANNELS.wikiGetStatus,
    IPC_CHANNELS.wikiSync,
    IPC_CHANNELS.wikiSearch,
    IPC_CHANNELS.wikiReadSource,
  ],
  story: [
    IPC_CHANNELS.storyGetState,
    IPC_CHANNELS.storyCreatePlot,
    IPC_CHANNELS.storyUpdatePlot,
    IPC_CHANNELS.storyDeletePlot,
    IPC_CHANNELS.storyCreateNode,
    IPC_CHANNELS.storyUpdateNode,
    IPC_CHANNELS.storyDeleteNode,
    IPC_CHANNELS.storyCreateEdge,
    IPC_CHANNELS.storyDeleteEdge,
  ],
  chapter: [
    IPC_CHANNELS.chapterGetDocument,
    IPC_CHANNELS.chapterSaveDocument,
    IPC_CHANNELS.chapterExportDocx,
    IPC_CHANNELS.chapterPrint,
    IPC_CHANNELS.chapterListCharacters,
    IPC_CHANNELS.chapterListLocations,
    IPC_CHANNELS.chapterListScenes,
  ],
  manuscript: [
    IPC_CHANNELS.manuscriptExportEpub,
    IPC_CHANNELS.manuscriptExportDocx,
    IPC_CHANNELS.manuscriptPrint,
  ],
  character: [
    IPC_CHANNELS.characterListCards,
    IPC_CHANNELS.characterCreateCard,
    IPC_CHANNELS.characterUpdateCard,
    IPC_CHANNELS.characterDeleteCard,
    IPC_CHANNELS.characterListChapterLinks,
    IPC_CHANNELS.characterSetChapterLinks,
    IPC_CHANNELS.characterGenerateImage,
    IPC_CHANNELS.characterListImages,
    IPC_CHANNELS.characterCreateImage,
    IPC_CHANNELS.characterDeleteImage,
  ],
  location: [
    IPC_CHANNELS.locationListCards,
    IPC_CHANNELS.locationCreateCard,
    IPC_CHANNELS.locationUpdateCard,
    IPC_CHANNELS.locationDeleteCard,
    IPC_CHANNELS.locationListChapterLinks,
    IPC_CHANNELS.locationSetChapterLinks,
    IPC_CHANNELS.locationGenerateImage,
    IPC_CHANNELS.locationListImages,
    IPC_CHANNELS.locationCreateImage,
    IPC_CHANNELS.locationDeleteImage,
  ],
  scene: [
    IPC_CHANNELS.sceneListCards,
    IPC_CHANNELS.sceneCreateCard,
    IPC_CHANNELS.sceneUpdateCard,
    IPC_CHANNELS.sceneDeleteCard,
  ],
  timeline: [
    IPC_CHANNELS.timelineGetState,
    IPC_CHANNELS.timelineUpdateSettings,
    IPC_CHANNELS.timelineUpdateItem,
  ],
  revision: [
    IPC_CHANNELS.revisionGetCurrent,
    IPC_CHANNELS.revisionCreate,
    IPC_CHANNELS.revisionList,
    IPC_CHANNELS.revisionRestore,
  ],
  codex: [
    IPC_CHANNELS.codexStatus,
    IPC_CHANNELS.codexGetSettings,
    IPC_CHANNELS.codexUpdateSettings,
    IPC_CHANNELS.codexAssist,
    IPC_CHANNELS.codexTransformSelection,
    IPC_CHANNELS.codexChat,
    IPC_CHANNELS.codexGetChatHistory,
    IPC_CHANNELS.codexClearChatHistory,
    IPC_CHANNELS.codexCancelActiveRequest,
  ],
} as const satisfies Record<string, readonly IpcChannelName[]>;

export const ALL_IPC_CHANNELS_BY_DOMAIN = Object.values(IPC_CHANNEL_GROUPS).flat();
